Revert "[iOS] Trigger a generic error page on lookalikes of top sites"
This reverts commit 66a6a9d911658ac13fd7725c1ca0f8b565dd4b42.

Reason for revert: Caused build failure:
https://ci.chromium.org/p/chromium/builders/ci/ios-device/155132
../../ios/components/security_interstitials/lookalikes/lookalike_url_tab_helper.mm:76:8: error: no matching function for call to 'GetMatchingDomain'
if (!GetMatchingDomain(navigated_domain, engaged_sites, &matched_domain,
^~~~~~~~~~~~~~~~~

Original change's description:
> [iOS] Trigger a generic error page on lookalikes of top sites
> 
> This currently triggers a net error since this is required for
> GetErrorPage, but will later be updated to pass a custom NSError.
> 
> Follow-up CLs will add the actual blocking page UI and incorporate
> site engagement once it's been turned into a component.
> 
> Bug: 1058898
> Change-Id: I36af8be93a8a42a4127ff5365d26c2a1aea5087a
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2166356
> Commit-Queue: Livvie Lin <livvielin@chromium.org>
> Reviewed-by: Mustafa Emre Acer <meacer@chromium.org>
> Reviewed-by: Matt Menke <mmenke@chromium.org>
> Reviewed-by: Rohit Rao <rohitrao@chromium.org>
> Reviewed-by: Kurt Horimoto <kkhorimoto@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#764518}

TBR=rohitrao@chromium.org,ajuma@chromium.org,meacer@chromium.org,mmenke@chromium.org,kkhorimoto@chromium.org,livvielin@chromium.org

Change-Id: Icd84b231f282d34aad0016704e8a544d039e15a8
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1058898
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2173848
Reviewed-by: Tsuyoshi Horo <horo@chromium.org>
Commit-Queue: Tsuyoshi Horo <horo@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#764523}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: f916c7b5a09173d79c665950d2d9c71d8c06997a